---
title: "flat_crypt_vector.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# crypt_vector

```{r development-crypt_vector}
# Prepare the code of your function here
```

```{r function-crypt_vector}
#' Encrypt a vector
#'
#' @param vector Vector to process
#' @param key Character 1L. Encryption key
#' @param algo Character 1L. Algorithm. 
#' See algo argument from digest::digest()
#' @return Character. Encrypted vector
#' @export
#'
crypt_vector <- function(vector, key, algo) {
  
  vector <- stringr::str_to_upper(vector)
  vector <- stringr::str_trim(vector)
  vector <- stringr::str_replace_all(vector, " ", "")
  
  vector_crypt <- sapply(
    paste0(vector, key), 
    \(x) digest::digest(x, algo = algo, serialize = FALSE))
  vector_crypt <- stringr::str_to_upper(vector_crypt)
  vector_crypt <- unname(vector_crypt)
  
  if (length(vector) != length(vector_crypt)) {
    stop("Something is wrong in the core of the encryption process. Please investigate.")
  }
  
  vector_crypt[nchar(vector) == 0 |
                 is.na(vector)] <- NA
  
  vector_crypt
}
# vérifié que ça donne les mêmes résultats que dans le présent module
```

```{r examples-crypt_vector}
crypt_vector(vector = c("1234", "5678", "9101112", NA, ""), key = "123456", algo = "md5")
```

```{r tests-crypt_vector}
test_that("Valid outputs are consistent", {
  
  input1 <- c(123, 456, 789)
  output1 <- c("1E191D851B3B49A248F4EA62F6B06410", 
               "F87003205DD342BEC2B81EE940172A4D", 
               "11A22927C85333CE98510B0FA1A1C27D")
  
  input2 <- c("abc", "def", NA)
  output2 <- c("09C74ADA9E6C9FBDEF249B258A66E948", "4FF225BA6F02CC8E5EB64E7647FBB7FC", NA)
  
  expect_identical(
    object = output1, 
    expected = crypt_vector(input1, key = "123456", algo = "md5")
  )
  
  expect_identical(
    object = output2, 
    expected = crypt_vector(input2, key = "123456", algo = "md5")
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_crypt_vector.Rmd", 
               vignette_name = NA)
```

