# WARNING - Generated by {fusen} from dev/flat_crypt_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Valid outputs are consistent", {
  
  output <- structure(list(
    mpg_crypt = c("CEA9D4F43791ACE22D90EDBF6CE405F5", 
                  "CEA9D4F43791ACE22D90EDBF6CE405F5", 
                  "65080BE2078D5C5934F018F806E72E81", 
                  "18C5941010E3CDCB669F472DF3A1DD5E", 
                  "1866EA523631A281BD9431915F7C407F"), 
    disp = c(160, 160, 108, 258, 360), 
    hp = c(110, 110, 93, 110, 175), 
    drat = c(3.9, 3.9, 3.85, 3.08, 3.15), 
    wt = c(2.62, 2.875, 2.32, 3.215, 3.44), 
    qsec = c(16.46, 17.02, 18.61, 19.44, 17.02), 
    vs = c(0, 0, 1, 1, 0), 
    am = c(1, 1, 1, 0, 0), 
    gear = c(4, 4, 4, 3, 3), 
    carb = c(4, 4, 1, 1, 2)), 
    class = "data.frame", 
    row.names = c("Mazda RX4", "Mazda RX4 Wag", "Datsun 710", 
                  "Hornet 4 Drive", "Hornet Sportabout"))
  
  expect_identical(object = output, 
                   expected = crypt_data(
                     loaded_dataset = mtcars[1:5, ], 
                     vars_to_encrypt = "mpg", 
                     vars_to_remove = "cyl", 
                     encryption_key = "1234567", 
                     algorithm = "md5", 
                     correspondence_table = FALSE
                   ))
})

test_that("Errors are consistent", {
  
  expect_error(
    object = crypt_data(loaded_dataset = mtcars[1:5], 
                        vars_to_encrypt = "noexist", 
                        vars_to_remove = "cyl", 
                        encryption_key = "123456", 
                        algorithm = "md5", 
                        correspondence_table = FALSE),
    regexp = "All indicated vars_to_encrypt must be effectively a variable name."
  )
  
  expect_error(
    object = crypt_data(loaded_dataset = mtcars[1:5], 
                        vars_to_encrypt = "mpg", 
                        vars_to_remove = "noexist", 
                        encryption_key = "123456", 
                        algorithm = "md5", 
                        correspondence_table = FALSE),
    regexp = "All indicated vars_to_remove must be effectively a variable name."
  )
})
