# WARNING - Generated by {fusen} from dev/flat_crypt_vector.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Valid outputs are consistent", {
  
  input1 <- c(123, 456, 789)
  output1 <- c("1E191D851B3B49A248F4EA62F6B06410", 
               "F87003205DD342BEC2B81EE940172A4D", 
               "11A22927C85333CE98510B0FA1A1C27D")
  
  input2 <- c("abc", "def", NA)
  output2 <- c("09C74ADA9E6C9FBDEF249B258A66E948", "4FF225BA6F02CC8E5EB64E7647FBB7FC", NA)
  
  expect_identical(
    object = output1, 
    expected = crypt_vector(input1, key = "123456", algo = "md5")
  )
  
  expect_identical(
    object = output2, 
    expected = crypt_vector(input2, key = "123456", algo = "md5")
  )
})
