# WARNING - Generated by {fusen} from dev/flat_assign_to_global.Rmd: do not edit by hand # nolint: line_length_linter.

#' Assign to global environment (internal, deprecated).
#'
#' Historically used by the pre-1.D.6.b `crypt_r()` orchestrator to
#' bridge `job::job()` subprocess results back into the calling R
#' session via `globalenv()`. Phase 1.D.6.b replaced that pattern with
#' `mirai` (values flow through serialized return-values) and with the
#' package-private `.cryptRopen_env` for correspondence tables. The
#' function is kept as an internal helper to avoid an abrupt removal
#' that could break downstream code still referencing it, but it is no
#' longer exported and is not used anywhere in the package.
#'
#' @param name Character. Name to assign the object.
#' @param object Object to assign to the name.
#' @param pos Integer 1L.
#'
#' @return Invisibly, the result of `assign()`.
#' @keywords internal
#' @noRd
#' @source https://stackoverflow.com/questions/28180989/r-cmd-check-found-the-following-assignments-to-the-global-environment
#'
assign_to_global <- function(name, object, pos = 1L) {
  (function (name, object, pos)
    assign(name, object, envir = as.environment(pos)))(name, object, pos = pos)
}
