# WARNING - Generated by {fusen} from dev/flat_crypt_vector.Rmd: do not edit by hand # nolint: line_length_linter.

#' Encrypt a vector
#'
#' @param vector Vector to process
#' @param key Character 1L. Encryption key
#' @param algo Character 1L. Algorithm.
#' See algo argument from digest::digest()
#' @return Character. Encrypted vector
#' @export
#'
#' @examples
#' crypt_vector(vector = c("1234", "5678", "9101112", NA, ""), key = "123456", algo = "md5")
crypt_vector <- function(vector, key, algo) {

  normalized <- .normalize_crypt_input(vector)
  mask_na    <- is.na(normalized) | nchar(normalized) == 0L

  out <- rep(NA_character_, length(normalized))
  hashes <- vapply(
    paste0(normalized[!mask_na], key),
    function(x) digest::digest(x, algo = algo, serialize = FALSE),
    character(1L),
    USE.NAMES = FALSE
  )
  out[!mask_na] <- stringr::str_to_upper(hashes)

  out
}

#' Normalize a vector before encryption
#'
#' Applies the deterministic pre-hash normalization:
#' upper-case, trim, remove internal spaces. Coerces to character
#' if needed (via stringr). NAs stay NA.
#'
#' @param x Atomic vector.
#' @return Character vector of same length as `x`.
#' @keywords internal
#' @noRd
.normalize_crypt_input <- function(x) {
  x <- stringr::str_to_upper(x)
  x <- stringr::str_trim(x)
  stringr::str_replace_all(x, " ", "")
}
