# WARNING - Generated by {fusen} from dev/flat_crypt_vector.Rmd: do not edit by hand # nolint: line_length_linter.

#' Encrypt a vector
#'
#' @param vector Vector to process
#' @param key Character 1L. Encryption key
#' @param algo Character 1L. Algorithm. 
#' See algo argument from digest::digest()
#' @return Character. Encrypted vector
#' @export
#'
#' @examples
#' crypt_vector(vector = c("1234", "5678", "9101112", NA, ""), key = "123456", algo = "md5")
crypt_vector <- function(vector, key, algo) {
  
  vector <- stringr::str_to_upper(vector)
  vector <- stringr::str_trim(vector)
  vector <- stringr::str_replace_all(vector, " ", "")
  
  vector_crypt <- sapply(
    paste0(vector, key), 
    \(x) digest::digest(x, algo = algo, serialize = FALSE))
  vector_crypt <- stringr::str_to_upper(vector_crypt)
  vector_crypt <- unname(vector_crypt)
  
  if (length(vector) != length(vector_crypt)) {
    stop("Something is wrong in the core of the encryption process. Please investigate.")
  }
  
  vector_crypt[nchar(vector) == 0 |
                 is.na(vector)] <- NA
  
  vector_crypt
}
# vérifié que ça donne les mêmes résultats que dans le présent module
