# WARNING - Generated by {fusen} from dev/flat_crypt_r.Rmd: do not edit by hand # nolint: line_length_linter.

#' Industrialized dataset variables encryption.
#'
#' This function consolidates a set of procedures
#' made to encrypt variables from datasets.
#' Variables to encrypt and input datasets can be in any number,
#' following user's needs.
#' The design tries to approach parallel processing.
#'
#' @param mask_folder_path Folder path of the excel mask.
#' @param mask_file File name (with extension) of the excel mask.
#' @param output_path Folder path where the encrypted datasets
#' will be created.
#' @param intermediate_path Folder path where intermediate files
#' (correspondence tables for e.g) will be created.
#' @param encryption_key Character vector.
#' @param algorithm Algorithm to use.
#' From digest::digest()'s algo argument.
#' @param correspondence_table Logical vector. If TRUE, the correspondence tables will computed
#' and stored in the indicated intermediate_path.
#' @param engine One of `"auto"`, `"in_memory"`, `"streaming"`.
#'   Selects the per-row processing engine. `"auto"` (default) and
#'   `"streaming"` both route parquet-in/parquet-out and csv-in/csv-out
#'   to the streaming engines (arrow Scanner by chunks, progressive
#'   write); mixed or non-streamable endpoints (rds, xlsx, parquet→csv,
#'   csv→parquet) silently fall back to `"in_memory"` to preserve
#'   non-regression. `"in_memory"` always reads the full input into
#'   RAM (historical behaviour). Introduced in Phase 1.D.4.a
#'   (plumbing), streaming engines in 1.D.4.b/c, auto-routing rule in
#'   1.D.4.d.
#' @param chunk_size Integer. Number of rows per chunk when the
#'   effective engine is streaming. Ignored by `"in_memory"` (and by
#'   `"auto"` / `"streaming"` when falling back to in_memory). Default
#'   `1e6`.
#' @importFrom magrittr %>%
#' @export
#'
crypt_r <- function (mask_folder_path, mask_file,
                     output_path, intermediate_path,
                     encryption_key, algorithm = "md5",
                     correspondence_table = TRUE,
                     engine = c("auto", "in_memory", "streaming"),
                     chunk_size = 1e6L) {

  requireNamespace("magrittr")

  engine <- match.arg(engine)
  stopifnot(is.numeric(chunk_size),
            length(chunk_size) == 1L,
            !is.na(chunk_size),
            chunk_size > 0)
  chunk_size <- as.integer(chunk_size)

  # The Excel mask:
  mask <-
    rio::import(file.path(mask_folder_path, mask_file)) %>%

    # Without eventual blank lines in the mask (for visualization ease):
    dplyr::filter_all(dplyr::any_vars(! is.na(.))) %>%

    # Inserting a row_number (useful for technical reasons):
    dplyr::mutate(row_number = dplyr::row_number()) %>%

    # Keep only lines on datasets the user want to encrypt:
    dplyr::filter(to_encrypt == "X")

  # Check eventual duplicated file names, if there is, add indication
  # to keep file names unique:
  mask <-

    dplyr::mutate(
      mask,
      dupl_encrypted_file = duplicated(encrypted_file),
      ndupl_encrypted_file = cumsum(dupl_encrypted_file) %>%
        (\(n) paste0("DUPL", n)),
      encrypted_file =
        ifelse(dupl_encrypted_file,
               paste0(ndupl_encrypted_file, "_",
                      encrypted_file),
               encrypted_file))

  # Split the mask with r rows into a list of r elements, named by full
  # input file path:
  split_mask <-
    split(mask, mask$row_number) %>%
    stats::setNames(paste0(mask$folder_path, "/", mask$file))

  # Dispatch each row to its own background job. The per-row processing
  # logic lives in .process_mask_row() — extracted in Phase 1.D.1 so it
  # can be tested in isolation and swapped for in_memory / streaming
  # engines in Phases 1.D.2 / 1.D.4. The job::job() wrapper will itself
  # be replaced by mirai in Phase 1.D.6.
  purrr::map(names(split_mask), \(x) {

    # Sink args into the local frame so job::job() captures them.
    sm                   <- split_mask[[x]]
    input_path           <- x
    output_path          <- output_path
    intermediate_path    <- intermediate_path
    encryption_key       <- encryption_key
    algorithm            <- algorithm
    correspondence_table <- correspondence_table
    engine               <- engine
    chunk_size           <- chunk_size

    job::job({
      .process_mask_row(
        sm                   = sm,
        input_path           = input_path,
        output_path          = output_path,
        intermediate_path    = intermediate_path,
        encryption_key       = encryption_key,
        algorithm            = algorithm,
        correspondence_table = correspondence_table,
        engine               = engine,
        chunk_size           = chunk_size
      )
      job::export("none")
    },
    title = paste0("Encryption of ",
                   input_path %>% strsplit("/") %>%
                     purrr::map(\(xx) xx[length(xx)]) %>%
                     unlist()))
  })

  invisible(NULL)
}

#' Does the given path have a `.parquet` extension?
#'
#' Used by the dispatcher to decide whether the streaming engine is
#' applicable. Comparison is case-insensitive. No I/O — purely a name
#' check; actual openability is handled by arrow at read time.
#'
#' @param path Character(1).
#' @return Logical(1).
#' @noRd
.is_parquet <- function(path) {
  if (length(path) != 1L || is.na(path)) return(FALSE)
  grepl("\\.parquet$", path, ignore.case = TRUE)
}

#' Does the given path have a `.csv` extension?
#'
#' Symmetric helper to `.is_parquet()`, introduced in Phase 1.D.4.c
#' so the dispatcher can enable the CSV streaming engine.
#'
#' @param path Character(1).
#' @return Logical(1).
#' @noRd
.is_csv <- function(path) {
  if (length(path) != 1L || is.na(path)) return(FALSE)
  grepl("\\.csv$", path, ignore.case = TRUE)
}

#' Process one row of the encryption mask (dispatcher).
#'
#' Thin dispatcher introduced in Phase 1.D.2 and progressively extended:
#' 1.D.4.b (parquet streaming), 1.D.4.c (csv streaming), 1.D.4.d
#' (auto-routing rule + streaming helpers factorised).
#'
#' Routing rule (Phase 1.D.4.d):
#'   - `engine == "in_memory"` → always routes to
#'     `.process_mask_row_in_memory()` (historical code path).
#'   - `engine %in% c("auto", "streaming")` → tries streaming:
#'       * parquet-in + parquet-out → `.process_mask_row_streaming()`;
#'       * csv-in     + csv-out     → `.process_mask_row_csv_streaming()`;
#'       * mixed or non-streamable endpoints (rds, xlsx, parquet→csv,
#'         csv→parquet, …) → silent fallback to
#'         `.process_mask_row_in_memory()` to preserve non-regression.
#'
#' `"auto"` and `"streaming"` are functionally equivalent after
#' 1.D.4.d. The distinction is kept for clarity: `"auto"` is the
#' default promising smart routing; `"streaming"` is an explicit
#' opt-in. We deliberately do **not** make `"streaming"` strict
#' (i.e. erroring on non-streamable inputs) — that would be an API
#' change not authorised by CLAUDE.md.
#'
#' Keeping the dispatcher separate from the engines guarantees that
#' the historical code path stays untouched while the streaming
#' engines evolve, protecting non-regression on existing baselines.
#'
#' @inheritParams .process_mask_row_in_memory
#' @param engine One of `"auto"`, `"in_memory"`, `"streaming"`. See
#'   routing rules above.
#' @param chunk_size Integer. Forwarded to the streaming engines only;
#'   ignored by in_memory.
#' @return Invisible `NULL`.
#' @noRd
.process_mask_row <- function(sm, input_path, output_path, intermediate_path,
                              encryption_key, algorithm, correspondence_table,
                              engine = "in_memory", chunk_size = 1e6L) {

  try_stream <- engine %in% c("auto", "streaming")
  out_file   <- sm[["encrypted_file"]]

  use_parquet_stream <- try_stream &&
                        .is_parquet(input_path) &&
                        .is_parquet(out_file)
  use_csv_stream     <- try_stream &&
                        .is_csv(input_path) &&
                        .is_csv(out_file)

  if (use_parquet_stream) {
    .process_mask_row_streaming(
      sm                   = sm,
      input_path           = input_path,
      output_path          = output_path,
      intermediate_path    = intermediate_path,
      encryption_key       = encryption_key,
      algorithm            = algorithm,
      correspondence_table = correspondence_table,
      chunk_size           = chunk_size
    )
  } else if (use_csv_stream) {
    .process_mask_row_csv_streaming(
      sm                   = sm,
      input_path           = input_path,
      output_path          = output_path,
      intermediate_path    = intermediate_path,
      encryption_key       = encryption_key,
      algorithm            = algorithm,
      correspondence_table = correspondence_table,
      chunk_size           = chunk_size
    )
  } else {
    # Fallback: `engine = "in_memory"`, or streaming requested on a
    # non-streamable input (rds, xlsx, etc.) or mixed endpoints
    # (parquet→csv, csv→parquet). Historical engine preserves
    # non-regression behaviour in all these cases.
    .process_mask_row_in_memory(
      sm                   = sm,
      input_path           = input_path,
      output_path          = output_path,
      intermediate_path    = intermediate_path,
      encryption_key       = encryption_key,
      algorithm            = algorithm,
      correspondence_table = correspondence_table
    )
  }
}

#' Process one row of the encryption mask — in-memory engine.
#'
#' Encapsulates the **historical** per-row processing logic: full load
#' of the input file into RAM via `rio::import()`, then character
#' cleanup, encryption of the requested variables, optional
#' correspondence table, and export of the final dataset + inspect
#' report. Extracted from `.process_mask_row()` in Phase 1.D.2 so that
#' the historical code path can stay strictly unchanged while the
#' streaming engine is being written in Phase 1.D.4. The parallel
#' streaming engine will live in a sibling helper
#' `.process_mask_row_streaming()`.
#'
#' @section FROZEN (Phase 1.D.3):
#' The behaviour of this function is locked by:
#'   - `tests/baseline/outputs/` (byte-level fixtures regenerated by
#'     `tests/baseline/generate_baseline.R`), and
#'   - the explicit invariant tests at the bottom of
#'     `tests/testthat/test-process_mask_row.R` (inspect xlsx layout,
#'     TC parquet distinctness, output column order).
#'
#' Do **not** edit this function for refactoring, style, or
#' "improvement" reasons. Any behavioural change — even cosmetic —
#' requires:
#'   1. A ticketed motivation in the phase plan (not an opportunistic
#'      cleanup).
#'   2. Regeneration of `tests/baseline/outputs/` in the same commit.
#'   3. Review of the impact on the private (enterprise) branch that
#'      consumes this package.
#' The `assign_to_global()` + `eval(parse(text=))` patterns below are
#' historical debt that will be retired only in Phase 1.D.6 together
#' with the move to `mirai`; until then they are intentional.
#'
#' Side effects are preserved from the historical implementation: the
#' per-variable `<var>_crypt` vectors, the final
#' `<encrypted_file_sans_ext>` dataset and (when
#' `correspondence_table = TRUE`) the `tc_<encrypted_file_sans_ext>`
#' are still assigned to `globalenv()` via `assign_to_global()`. These
#' assignments will disappear in Phase 1.D.6 (values flowing through
#' return-values and `.cryptRopen_env` instead).
#'
#' @param sm A one-row data.frame corresponding to one row of the
#'   filtered mask (columns: folder_path, file, encrypted_file,
#'   vars_to_encrypt, vars_to_remove, …).
#' @param input_path Full path to the input dataset file.
#' @param output_path,intermediate_path Directories where outputs are written.
#' @param encryption_key,algorithm,correspondence_table Forwarded from
#'   `crypt_r()`.
#' @return Invisible `NULL`. All outputs are side effects (files on
#'   disk and assignments in `globalenv()`).
#' @noRd
.process_mask_row_in_memory <- function(sm, input_path, output_path, intermediate_path,
                                        encryption_key, algorithm, correspondence_table) {

  requireNamespace("magrittr")

  try({
    # Import and clean:
    assign_to_global(
      sm[["encrypted_file"]] %>% stringr::str_remove("\\..*$"),
      rio::import(input_path, trust = TRUE) %>%
        # 0-length values into NAs:
        dplyr::mutate_if(is.character, \(x0) {
          x0[nchar(stringr::str_trim(x0)) == 0] <- NA ;
          stringr::str_trim(x0)
        }) %>%
        # Encrypt:
        (\(x3) {

          # Each variable to encrypt in a vector:
          vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
            stringr::str_split(",") %>% unlist %>%
            stringr::str_trim()

          purrr::map(vars_to_encrypt, \(v) {

            # Encryption algorithm using the digest:: package:
            assign_to_global(paste0(v, "_crypt"),
                   crypt_vector(vector = x3[[v]],
                                key = encryption_key,
                                algo = algorithm),
                   pos = globalenv())
          })

          # Fuse initial dataset and encrypted variables:
          assign_to_global(
            sm[["encrypted_file"]] %>%
              stringr::str_remove("\\..*$"),
            dplyr::bind_cols(
                purrr::map(vars_to_encrypt %>%
                             paste0("_crypt"), get) %>%
                  do.call(what = dplyr::bind_cols) %>%
                  stats::setNames(vars_to_encrypt %>%
                                    paste0("_crypt")),
                x3) %>%
              dplyr::as_tibble() %>%

              # Correspondence table:
              (\(d) {
                if (! correspondence_table) {d} else {
                  purrr::map(vars_to_encrypt, \(v2) {
                    assign_to_global(
                      sm[["encrypted_file"]] %>%
                        stringr::str_remove("\\..*$") %>%
                        (\(x4) paste0("tc_", x4)),
                      dplyr::select(d,
                                    vars_to_encrypt) %>%
                        dplyr::bind_cols(
                          purrr::map(
                            vars_to_encrypt %>%
                              paste0("_crypt"), get) %>%
                            do.call(
                              what = dplyr::bind_cols) %>%
                            stats::setNames(
                              vars_to_encrypt %>%
                                paste0("_crypt"))) %>%
                        dplyr::distinct(),
                      pos = globalenv()
                    )
                  })

                  # Export into intermediate folder:
                  rio::export(
                    sm[["encrypted_file"]] %>%
                      stringr::str_remove("\\..*$") %>%
                      (\(x4)
                        paste0("tc_", x4)) %>% get(),

                    file.path(intermediate_path,
                              sm[["encrypted_file"]] %>%
                                stringr::str_remove(
                                  "\\..*$") %>%
                                (\(x4)
                                  paste0("tc_", x4)) %>%
                                paste0(".parquet"))
                  )
                  d
                }
              }) %>%

              # Output without original variables:
              dplyr::select(- vars_to_encrypt) %>%

              # Without any other variables user want to remove
              # from output, if applicable:
              (\(dfin) {
                vars_to_remove <- sm[["vars_to_remove"]] %>%
                  stringr::str_split(",") %>% unlist %>%
                  stringr::str_trim()

                if (all(is.na(vars_to_remove))) {
                  dfin
                } else {
                  dplyr::select(dfin, - vars_to_remove)
                }
              }),
            pos = globalenv())
        }
        )
    )
  })
  invisible()

  # Export final output:
  try({
    rio::export(
      eval(parse(text = sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))),
      file.path(output_path,
                sm[["encrypted_file"]]))
  })

  # Inspect final output:
  try({
    writexl::write_xlsx(
      eval(parse(text =  sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))) %>%
        (\(g)
          inspect(g) %>%
            (\(i) rbind(c("Obs = ", nrow(g),
                          rep("", ncol(i) - 1)),
                        c("Nvars = ", nrow(i),
                          rep("", ncol(i) - 1)),
                        cbind(1:nrow(i), i)))),
      file.path(output_path,
                paste0("inspect_", sm[["encrypted_file"]],
                       ".xlsx"))
    )
  })

  invisible(NULL)
}

#' Transform a single stream chunk: cleanup + crypt + column assembly.
#'
#' Introduced in Phase 1.D.4.d to factorise the ~80 lines previously
#' duplicated between `.process_mask_row_streaming()` (parquet) and
#' `.process_mask_row_csv_streaming()` (csv). Pure function — no I/O,
#' no globalenv / .cryptRopen_env side effect.
#'
#' Transformation steps (byte-for-byte identical to the historical
#' in_memory engine on matching inputs):
#'   1. Character cleanup: `str_trim()` then empty strings → `NA`.
#'   2. Per-variable encryption via `crypt_vector()`.
#'   3. Column assembly: `<var>_crypt` columns first in `vars_to_encrypt`
#'      order, then non-encrypted input columns in input order.
#'   4. Optional `vars_to_remove` drop (intersect-based — missing
#'      columns are silently ignored, matching in_memory behaviour).
#'
#' The returned `tc_chunk` is already `distinct()`. The caller merges
#' chunks across iterations with an outer `bind_rows %>% distinct`.
#'
#' @param chunk A tibble / data.frame — one scanner batch.
#' @param vars_to_encrypt,vars_to_remove Character vectors (as split
#'   from the mask row and trimmed).
#' @param encryption_key,algorithm Forwarded to `crypt_vector()`.
#' @param correspondence_table Logical(1). Controls whether `tc_chunk`
#'   is computed (`NULL` when `FALSE`).
#' @return A named list: `out_chunk` (tibble ready to write) and
#'   `tc_chunk` (tibble or `NULL`).
#' @noRd
.transform_stream_chunk <- function(chunk, vars_to_encrypt, vars_to_remove,
                                    encryption_key, algorithm,
                                    correspondence_table) {

  # 1. Character cleanup — trim + empty-string-to-NA.
  chunk <- dplyr::mutate(
    chunk,
    dplyr::across(dplyr::where(is.character), \(x0) {
      x0[nchar(stringr::str_trim(x0)) == 0] <- NA
      stringr::str_trim(x0)
    })
  )

  # 2. Encrypt each requested variable.
  crypted <- purrr::map(vars_to_encrypt, \(v) {
    crypt_vector(vector = chunk[[v]], key = encryption_key,
                 algo = algorithm)
  })
  names(crypted) <- paste0(vars_to_encrypt, "_crypt")
  crypted_df <- dplyr::as_tibble(crypted)

  # 3. Per-chunk correspondence rows (if requested).
  tc_chunk <- NULL
  if (correspondence_table) {
    tc_chunk <- dplyr::distinct(
      dplyr::bind_cols(
        dplyr::select(chunk, dplyr::all_of(vars_to_encrypt)),
        crypted_df
      )
    )
  }

  # 4. Assemble output: <var>_crypt first, non-encrypted in input order,
  #    then vars_to_remove dropped.
  non_enc_cols <- setdiff(names(chunk), vars_to_encrypt)
  out_chunk    <- dplyr::bind_cols(
    crypted_df,
    dplyr::select(chunk, dplyr::all_of(non_enc_cols)))

  if (!all(is.na(vars_to_remove))) {
    to_drop <- intersect(vars_to_remove, names(out_chunk))
    if (length(to_drop) > 0L) {
      out_chunk <- dplyr::select(out_chunk, -dplyr::all_of(to_drop))
    }
  }

  list(out_chunk = out_chunk, tc_chunk = tc_chunk)
}

#' Finalise the accumulated correspondence table: store in the package
#' private env + export to parquet on disk.
#'
#' Introduced in Phase 1.D.4.d. Extracted from the two streaming
#' engines whose post-loop finalisation was identical. Idempotent — a
#' no-op when `correspondence_table` is `FALSE` or when no rows were
#' accumulated.
#'
#' @param tc_accum The accumulated correspondence tibble, or `NULL`.
#' @param intermediate_path Directory for the parquet output.
#' @param encrypted_stem The encrypted file stem (extension stripped).
#' @param correspondence_table Logical(1).
#' @return Invisible `NULL`.
#' @noRd
.finalize_stream_tc <- function(tc_accum, intermediate_path, encrypted_stem,
                                correspondence_table) {
  if (!correspondence_table || is.null(tc_accum)) return(invisible(NULL))

  tc_name <- paste0("tc_", encrypted_stem)
  .store_correspondence_table(name = tc_name, df = tc_accum)
  arrow::write_parquet(
    tc_accum,
    file.path(intermediate_path,
              paste0(tc_name, ".parquet")))
  invisible(NULL)
}

#' Re-read a freshly written streamed output and emit the companion
#' `inspect_*.xlsx` report.
#'
#' Introduced in Phase 1.D.4.d. Both streaming engines rely on a
#' relecture-based inspect (chunks are not kept in RAM across the
#' scan).
#'
#' Relecture uses `rio::import()` — not arrow — to preserve strict
#' semantic non-regression with the in_memory engine. Rationale: the
#' in_memory engine calls `inspect()` on the pre-export tibble whose
#' types come from `rio::import()` (e.g. `data.table::fread` for CSV
#' returns `class = c("IDate", "Date")` on date columns, which makes
#' `inspect()` emit two rows per column via its `class`-vectorisation).
#' A prior implementation using `arrow::read_parquet` /
#' `arrow::read_csv_arrow` produced different `class()` tuples and
#' broke the baseline `compare_inspect()` comparison on 11 cases.
#' Reloading via `rio::import()` on the freshly written output
#' reproduces the historical type vector on both readers.
#'
#' Layout (identical to the in_memory engine):
#'   row 1 — writexl header artefact (column names),
#'   row 2 — `"Obs = "` + total row count,
#'   row 3 — `"Nvars = "` + inspect() row count,
#'   rows 4+ — inspect() output indexed by row number.
#'
#' @param output_file_path Full path to the encrypted output file.
#' @param output_path Directory where the xlsx will be written.
#' @param encrypted_file Base name of the encrypted file (with
#'   extension) — used to build the `inspect_*.xlsx` filename.
#' @return Invisible `NULL`. No-op if the output file is absent.
#' @noRd
.write_stream_inspect <- function(output_file_path,
                                  output_path, encrypted_file) {
  if (!file.exists(output_file_path)) return(invisible(NULL))

  out_df <- as.data.frame(rio::import(output_file_path, trust = TRUE))
  i <- inspect(out_df)
  # NB. The `1:nrow(i)` spelling (not `seq_len(nrow(i))`) is load-bearing:
  # `cbind()` names the new column from the *expression* passed to it, so
  # the historical in_memory engine emits a data.frame whose first column
  # is named "1:nrow(i)". writexl writes this name as the header row, which
  # readxl::read_xlsx(col_names = FALSE) then surfaces as the value of
  # row 1, column 1 in the compared xlsx. Using any other expression
  # (seq_len(), seq.int()…) breaks baseline on this single cell.
  layout <- rbind(
    c("Obs = ",   nrow(out_df), rep("", ncol(i) - 1)),
    c("Nvars = ", nrow(i),      rep("", ncol(i) - 1)),
    cbind(1:nrow(i), i))
  writexl::write_xlsx(
    layout,
    file.path(output_path,
              paste0("inspect_", encrypted_file, ".xlsx")))
  invisible(NULL)
}

#' Process one row of the encryption mask — streaming engine (parquet).
#'
#' Introduced in Phase 1.D.4.b, refactored in 1.D.4.d to delegate
#' chunk transformation, TC finalisation and inspect reporting to
#' shared helpers (`.transform_stream_chunk()`, `.finalize_stream_tc()`,
#' `.write_stream_inspect()`).
#'
#' Streams the input parquet file through an arrow Scanner by chunks
#' of `chunk_size` rows, encrypts each chunk in memory, writes the
#' result incrementally to the output parquet file via
#' `arrow::ParquetFileWriter`, and builds the correspondence table by
#' accumulating per-chunk `distinct()` rows.
#'
#' Handles **parquet-in / parquet-out only** (dispatcher precondition).
#'
#' Behavioural guarantees (vs. the in-memory engine on matching input):
#'   - Output rows identical (same values, same types, same order).
#'   - Output column order identical: `<var>_crypt` first in
#'     `vars_to_encrypt` order, then remaining input columns in input
#'     order (`vars_to_remove` applied last).
#'   - Character cleanup identical: `str_trim()` + empty → NA.
#'   - Correspondence table contents identical (modulo row order, also
#'     non-deterministic in the in-memory engine).
#'   - `inspect_*.xlsx` layout identical.
#'
#' Deliberate differences (Option B, validated 2026-04-22):
#'   - **No pollution of `globalenv()`**. TC lives in `.cryptRopen_env`
#'     (retrievable via `get_correspondence_tables()`) and on disk.
#'   - `assign_to_global()` + `eval(parse(text = ...))` are not used.
#'
#' @param sm,input_path,output_path,intermediate_path,encryption_key,algorithm,correspondence_table
#'   Forwarded from the dispatcher — see `.process_mask_row_in_memory()`.
#' @param chunk_size Integer(1). Arrow Scanner `batch_size`. Only
#'   affects memory usage and performance; results are invariant.
#' @return Invisible `NULL`. Side effects: files on disk + one entry
#'   in `.cryptRopen_env` when `correspondence_table = TRUE`.
#' @noRd
.process_mask_row_streaming <- function(sm, input_path, output_path, intermediate_path,
                                        encryption_key, algorithm, correspondence_table,
                                        chunk_size = 1e6L) {

  requireNamespace("magrittr")
  requireNamespace("arrow")

  encrypted_file   <- sm[["encrypted_file"]]
  encrypted_stem   <- stringr::str_remove(encrypted_file, "\\..*$")
  output_file_path <- file.path(output_path, encrypted_file)

  vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  vars_to_remove <- sm[["vars_to_remove"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  tc_accum <- NULL
  writer   <- NULL
  sink     <- NULL

  # --- Read / transform / write by chunks -------------------------------
  try({
    ds      <- arrow::open_dataset(input_path, format = "parquet")
    scanner <- arrow::Scanner$create(ds, batch_size = as.integer(chunk_size))
    reader  <- scanner$ToRecordBatchReader()

    repeat {
      batch <- reader$read_next_batch()
      if (is.null(batch)) break

      chunk <- dplyr::as_tibble(as.data.frame(batch))
      tf    <- .transform_stream_chunk(
        chunk                = chunk,
        vars_to_encrypt      = vars_to_encrypt,
        vars_to_remove       = vars_to_remove,
        encryption_key       = encryption_key,
        algorithm            = algorithm,
        correspondence_table = correspondence_table)

      if (correspondence_table && !is.null(tf$tc_chunk)) {
        tc_accum <- if (is.null(tc_accum)) tf$tc_chunk
                    else dplyr::distinct(dplyr::bind_rows(tc_accum, tf$tc_chunk))
      }

      arrow_tbl <- arrow::as_arrow_table(tf$out_chunk)

      # First chunk fixes the output schema; subsequent chunks must
      # conform. Character cleanup + crypt_vector() are type-stable,
      # so the schema is stable across chunks by construction.
      # Arrow-R quirks (see 1.D.4.b commit 38d8151d):
      #   - `sink` must be an OutputStream (a character path is not
      #     accepted — hence the FileOutputStream wrapper);
      #   - the default `properties` built by
      #     `ParquetWriterProperties$create()` fails unless
      #     `column_names` is provided explicitly;
      #   - `WriteTable()` also requires a non-default `chunk_size`.
      if (is.null(writer)) {
        sink   <- arrow::FileOutputStream$create(output_file_path)
        writer <- arrow::ParquetFileWriter$create(
          schema     = arrow_tbl$schema,
          sink       = sink,
          properties = arrow::ParquetWriterProperties$create(
            column_names = names(arrow_tbl)))
      }
      writer$WriteTable(arrow_tbl, chunk_size = arrow_tbl$num_rows)
    }

    if (!is.null(writer)) writer$Close()
    if (!is.null(sink))   sink$close()
  })

  # --- Correspondence table (shared finaliser) --------------------------
  try({
    .finalize_stream_tc(tc_accum, intermediate_path, encrypted_stem,
                        correspondence_table)
  })

  # --- Inspect (shared; rio::import for type fidelity) ------------------
  try({
    .write_stream_inspect(output_file_path, output_path, encrypted_file)
  })

  invisible(NULL)
}

#' Process one row of the encryption mask — streaming engine (CSV).
#'
#' Introduced in Phase 1.D.4.c, refactored in 1.D.4.d to share chunk
#' transformation / TC finalisation / inspect reporting with the
#' parquet streaming engine.
#'
#' Streams the input CSV via `arrow::open_csv_dataset()` + Scanner,
#' encrypts each chunk in memory, appends each chunk to the output CSV
#' via `utils::write.table(append = TRUE)`. `arrow::CsvWriter` is
#' intentionally not used: it is not exported in every installed
#' `arrow` version. `utils::write.table` preserves the streaming
#' property on the read/transform side with no extra dependency.
#'
#' Handles **csv-in / csv-out only** (dispatcher precondition). The
#' correspondence table is still written as parquet (symmetric with
#' in_memory + parquet streaming): only the main encrypted dataset is
#' CSV.
#'
#' Semantic guarantees vs. the in-memory engine: identical row set,
#' identical output column order, identical character cleanup rules.
#' **Byte-level equality is not guaranteed** — base R's writer quoting
#' rules differ from `rio::export()` / `data.table::fwrite`. Tests
#' compare via re-read content (`rowset()`), not by file hash.
#'
#' Like the parquet streaming engine: no globalenv pollution, TC in
#' `.cryptRopen_env` + on disk.
#'
#' @inheritParams .process_mask_row_streaming
#' @return Invisible `NULL`.
#' @noRd
.process_mask_row_csv_streaming <- function(sm, input_path, output_path, intermediate_path,
                                            encryption_key, algorithm, correspondence_table,
                                            chunk_size = 1e6L) {

  requireNamespace("magrittr")
  requireNamespace("arrow")

  encrypted_file   <- sm[["encrypted_file"]]
  encrypted_stem   <- stringr::str_remove(encrypted_file, "\\..*$")
  output_file_path <- file.path(output_path, encrypted_file)

  vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  vars_to_remove <- sm[["vars_to_remove"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  tc_accum    <- NULL
  first_chunk <- TRUE

  # --- Read / transform / write by chunks -------------------------------
  try({
    ds      <- arrow::open_csv_dataset(input_path)
    scanner <- arrow::Scanner$create(ds, batch_size = as.integer(chunk_size))
    reader  <- scanner$ToRecordBatchReader()

    repeat {
      batch <- reader$read_next_batch()
      if (is.null(batch)) break

      chunk <- dplyr::as_tibble(as.data.frame(batch))
      tf    <- .transform_stream_chunk(
        chunk                = chunk,
        vars_to_encrypt      = vars_to_encrypt,
        vars_to_remove       = vars_to_remove,
        encryption_key       = encryption_key,
        algorithm            = algorithm,
        correspondence_table = correspondence_table)

      if (correspondence_table && !is.null(tf$tc_chunk)) {
        tc_accum <- if (is.null(tc_accum)) tf$tc_chunk
                    else dplyr::distinct(dplyr::bind_rows(tc_accum, tf$tc_chunk))
      }

      # Append chunk to CSV output. First chunk writes the header and
      # creates the file; subsequent chunks append without header.
      utils::write.table(
        as.data.frame(tf$out_chunk),
        file      = output_file_path,
        sep       = ",",
        dec       = ".",
        qmethod   = "double",
        row.names = FALSE,
        col.names = first_chunk,
        append    = !first_chunk)
      first_chunk <- FALSE
    }
  })

  # --- Correspondence table (shared finaliser) --------------------------
  try({
    .finalize_stream_tc(tc_accum, intermediate_path, encrypted_stem,
                        correspondence_table)
  })

  # --- Inspect (shared; rio::import for type fidelity) ------------------
  try({
    .write_stream_inspect(output_file_path, output_path, encrypted_file)
  })

  invisible(NULL)
}
