# WARNING - Generated by {fusen} from dev/flat_crypt_r.Rmd: do not edit by hand # nolint: line_length_linter.

#' Industrialized dataset variables encryption.
#'
#' This function consolidates a set of procedures
#' made to encrypt variables from datasets.
#' Variables to encrypt and input datasets can be in any number,
#' following user's needs.
#' The design tries to approach parallel processing.
#'
#' @param mask_folder_path Folder path of the excel mask.
#' @param mask_file File name (with extension) of the excel mask.
#' @param output_path Folder path where the encrypted datasets
#' will be created.
#' @param intermediate_path Folder path where intermediate files
#' (correspondence tables for e.g) will be created.
#' @param encryption_key Character vector.
#' @param algorithm Algorithm to use.
#' From digest::digest()'s algo argument.
#' @param correspondence_table Logical vector. If TRUE, the correspondence tables will computed
#' and stored in the indicated intermediate_path.
#' @importFrom magrittr %>%
#' @export
#'
crypt_r <- function (mask_folder_path, mask_file,
                     output_path, intermediate_path,
                     encryption_key, algorithm = "md5",
                     correspondence_table = TRUE) {

  requireNamespace("magrittr")

  # The Excel mask:
  mask <-
    rio::import(file.path(mask_folder_path, mask_file)) %>%

    # Without eventual blank lines in the mask (for visualization ease):
    dplyr::filter_all(dplyr::any_vars(! is.na(.))) %>%

    # Inserting a row_number (useful for technical reasons):
    dplyr::mutate(row_number = dplyr::row_number()) %>%

    # Keep only lines on datasets the user want to encrypt:
    dplyr::filter(to_encrypt == "X")

  # Check eventual duplicated file names, if there is, add indication
  # to keep file names unique:
  mask <-

    dplyr::mutate(
      mask,
      dupl_encrypted_file = duplicated(encrypted_file),
      ndupl_encrypted_file = cumsum(dupl_encrypted_file) %>%
        (\(n) paste0("DUPL", n)),
      encrypted_file =
        ifelse(dupl_encrypted_file,
               paste0(ndupl_encrypted_file, "_",
                      encrypted_file),
               encrypted_file))

  # Split the mask with r rows into a list of r elements, named by full
  # input file path:
  split_mask <-
    split(mask, mask$row_number) %>%
    stats::setNames(paste0(mask$folder_path, "/", mask$file))

  # Dispatch each row to its own background job. The per-row processing
  # logic lives in .process_mask_row() — extracted in Phase 1.D.1 so it
  # can be tested in isolation and swapped for in_memory / streaming
  # engines in Phases 1.D.2 / 1.D.4. The job::job() wrapper will itself
  # be replaced by mirai in Phase 1.D.6.
  purrr::map(names(split_mask), \(x) {

    # Sink args into the local frame so job::job() captures them.
    sm                   <- split_mask[[x]]
    input_path           <- x
    output_path          <- output_path
    intermediate_path    <- intermediate_path
    encryption_key       <- encryption_key
    algorithm            <- algorithm
    correspondence_table <- correspondence_table

    job::job({
      .process_mask_row(
        sm                   = sm,
        input_path           = input_path,
        output_path          = output_path,
        intermediate_path    = intermediate_path,
        encryption_key       = encryption_key,
        algorithm            = algorithm,
        correspondence_table = correspondence_table
      )
      job::export("none")
    },
    title = paste0("Encryption of ",
                   input_path %>% strsplit("/") %>%
                     purrr::map(\(xx) xx[length(xx)]) %>%
                     unlist()))
  })

  invisible(NULL)
}

#' Process one row of the encryption mask (dispatcher).
#'
#' Thin dispatcher introduced in Phase 1.D.2. Today it only routes to
#' `.process_mask_row_in_memory()`, which encapsulates the historical
#' behaviour (full-file load into RAM). Phase 1.D.4 will add
#' `.process_mask_row_streaming()` and a user-facing `engine` parameter
#' on `crypt_r()` to select between them (with `"auto"` picking the
#' right engine from the input format).
#'
#' Keeping the dispatcher separate from the engine guarantees that the
#' historical code path stays strictly untouched while the streaming
#' engine is being written, protecting non-regression on existing
#' baselines.
#'
#' @inheritParams .process_mask_row_in_memory
#' @return Invisible `NULL`.
#' @noRd
.process_mask_row <- function(sm, input_path, output_path, intermediate_path,
                              encryption_key, algorithm, correspondence_table) {
  .process_mask_row_in_memory(
    sm                   = sm,
    input_path           = input_path,
    output_path          = output_path,
    intermediate_path    = intermediate_path,
    encryption_key       = encryption_key,
    algorithm            = algorithm,
    correspondence_table = correspondence_table
  )
}

#' Process one row of the encryption mask — in-memory engine.
#'
#' Encapsulates the **historical** per-row processing logic: full load
#' of the input file into RAM via `rio::import()`, then character
#' cleanup, encryption of the requested variables, optional
#' correspondence table, and export of the final dataset + inspect
#' report. Extracted from `.process_mask_row()` in Phase 1.D.2 so that
#' the historical code path can stay strictly unchanged while the
#' streaming engine is being written in Phase 1.D.4. The parallel
#' streaming engine will live in a sibling helper
#' `.process_mask_row_streaming()`.
#'
#' Side effects are preserved from the historical implementation: the
#' per-variable `<var>_crypt` vectors, the final
#' `<encrypted_file_sans_ext>` dataset and (when
#' `correspondence_table = TRUE`) the `tc_<encrypted_file_sans_ext>`
#' are still assigned to `globalenv()` via `assign_to_global()`. These
#' assignments will disappear in Phase 1.D.6 (values flowing through
#' return-values and `.cryptRopen_env` instead).
#'
#' @param sm A one-row data.frame corresponding to one row of the
#'   filtered mask (columns: folder_path, file, encrypted_file,
#'   vars_to_encrypt, vars_to_remove, …).
#' @param input_path Full path to the input dataset file.
#' @param output_path,intermediate_path Directories where outputs are written.
#' @param encryption_key,algorithm,correspondence_table Forwarded from
#'   `crypt_r()`.
#' @return Invisible `NULL`. All outputs are side effects (files on
#'   disk and assignments in `globalenv()`).
#' @noRd
.process_mask_row_in_memory <- function(sm, input_path, output_path, intermediate_path,
                                        encryption_key, algorithm, correspondence_table) {

  requireNamespace("magrittr")

  try({
    # Import and clean:
    assign_to_global(
      sm[["encrypted_file"]] %>% stringr::str_remove("\\..*$"),
      rio::import(input_path, trust = TRUE) %>%
        # 0-length values into NAs:
        dplyr::mutate_if(is.character, \(x0) {
          x0[nchar(stringr::str_trim(x0)) == 0] <- NA ;
          stringr::str_trim(x0)
        }) %>%
        # Encrypt:
        (\(x3) {

          # Each variable to encrypt in a vector:
          vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
            stringr::str_split(",") %>% unlist %>%
            stringr::str_trim()

          purrr::map(vars_to_encrypt, \(v) {

            # Encryption algorithm using the digest:: package:
            assign_to_global(paste0(v, "_crypt"),
                   crypt_vector(vector = x3[[v]],
                                key = encryption_key,
                                algo = algorithm),
                   pos = globalenv())
          })

          # Fuse initial dataset and encrypted variables:
          assign_to_global(
            sm[["encrypted_file"]] %>%
              stringr::str_remove("\\..*$"),
            dplyr::bind_cols(
                purrr::map(vars_to_encrypt %>%
                             paste0("_crypt"), get) %>%
                  do.call(what = dplyr::bind_cols) %>%
                  stats::setNames(vars_to_encrypt %>%
                                    paste0("_crypt")),
                x3) %>%
              dplyr::as_tibble() %>%

              # Correspondence table:
              (\(d) {
                if (! correspondence_table) {d} else {
                  purrr::map(vars_to_encrypt, \(v2) {
                    assign_to_global(
                      sm[["encrypted_file"]] %>%
                        stringr::str_remove("\\..*$") %>%
                        (\(x4) paste0("tc_", x4)),
                      dplyr::select(d,
                                    vars_to_encrypt) %>%
                        dplyr::bind_cols(
                          purrr::map(
                            vars_to_encrypt %>%
                              paste0("_crypt"), get) %>%
                            do.call(
                              what = dplyr::bind_cols) %>%
                            stats::setNames(
                              vars_to_encrypt %>%
                                paste0("_crypt"))) %>%
                        dplyr::distinct(),
                      pos = globalenv()
                    )
                  })

                  # Export into intermediate folder:
                  rio::export(
                    sm[["encrypted_file"]] %>%
                      stringr::str_remove("\\..*$") %>%
                      (\(x4)
                        paste0("tc_", x4)) %>% get(),

                    file.path(intermediate_path,
                              sm[["encrypted_file"]] %>%
                                stringr::str_remove(
                                  "\\..*$") %>%
                                (\(x4)
                                  paste0("tc_", x4)) %>%
                                paste0(".parquet"))
                  )
                  d
                }
              }) %>%

              # Output without original variables:
              dplyr::select(- vars_to_encrypt) %>%

              # Without any other variables user want to remove
              # from output, if applicable:
              (\(dfin) {
                vars_to_remove <- sm[["vars_to_remove"]] %>%
                  stringr::str_split(",") %>% unlist %>%
                  stringr::str_trim()

                if (all(is.na(vars_to_remove))) {
                  dfin
                } else {
                  dplyr::select(dfin, - vars_to_remove)
                }
              }),
            pos = globalenv())
        }
        )
    )
  })
  invisible()

  # Export final output:
  try({
    rio::export(
      eval(parse(text = sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))),
      file.path(output_path,
                sm[["encrypted_file"]]))
  })

  # Inspect final output:
  try({
    writexl::write_xlsx(
      eval(parse(text =  sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))) %>%
        (\(g)
          inspect(g) %>%
            (\(i) rbind(c("Obs = ", nrow(g),
                          rep("", ncol(i) - 1)),
                        c("Nvars = ", nrow(i),
                          rep("", ncol(i) - 1)),
                        cbind(1:nrow(i), i)))),
      file.path(output_path,
                paste0("inspect_", sm[["encrypted_file"]],
                       ".xlsx"))
    )
  })

  invisible(NULL)
}
