# WARNING - Generated by {fusen} from dev/flat_crypt_r.Rmd: do not edit by hand # nolint: line_length_linter.

#' Industrialized dataset variables encryption.
#'
#' This function consolidates a set of procedures
#' made to encrypt variables from datasets.
#' Variables to encrypt and input datasets can be in any number,
#' following user's needs.
#' The design tries to approach parallel processing.
#'
#' @param mask_folder_path Folder path of the excel mask.
#' @param mask_file File name (with extension) of the excel mask.
#' @param output_path Folder path where the encrypted datasets
#' will be created.
#' @param intermediate_path Folder path where intermediate files
#' (correspondence tables for e.g) will be created.
#' @param encryption_key Character vector.
#' @param algorithm Algorithm to use.
#' From digest::digest()'s algo argument.
#' @param correspondence_table Logical vector. If TRUE, the correspondence tables will computed
#' and stored in the indicated intermediate_path.
#' @param engine One of `"auto"`, `"in_memory"`, `"streaming"`.
#'   Selects the per-row processing engine. `"auto"` (default) picks
#'   `"streaming"` for `.parquet` / `.csv` inputs and `"in_memory"`
#'   for every other format. `"in_memory"` reads the full input into
#'   RAM (historical behaviour). `"streaming"` scans the input by
#'   chunks via arrow and writes progressively. Introduced in Phase
#'   1.D.4.a; the streaming engine itself lands in 1.D.4.b/c.
#' @param chunk_size Integer. Number of rows per chunk when `engine`
#'   resolves to `"streaming"`. Ignored by `"in_memory"`. Default
#'   `1e6`.
#' @importFrom magrittr %>%
#' @export
#'
crypt_r <- function (mask_folder_path, mask_file,
                     output_path, intermediate_path,
                     encryption_key, algorithm = "md5",
                     correspondence_table = TRUE,
                     engine = c("auto", "in_memory", "streaming"),
                     chunk_size = 1e6L) {

  requireNamespace("magrittr")

  engine <- match.arg(engine)
  stopifnot(is.numeric(chunk_size),
            length(chunk_size) == 1L,
            !is.na(chunk_size),
            chunk_size > 0)
  chunk_size <- as.integer(chunk_size)

  # The Excel mask:
  mask <-
    rio::import(file.path(mask_folder_path, mask_file)) %>%

    # Without eventual blank lines in the mask (for visualization ease):
    dplyr::filter_all(dplyr::any_vars(! is.na(.))) %>%

    # Inserting a row_number (useful for technical reasons):
    dplyr::mutate(row_number = dplyr::row_number()) %>%

    # Keep only lines on datasets the user want to encrypt:
    dplyr::filter(to_encrypt == "X")

  # Check eventual duplicated file names, if there is, add indication
  # to keep file names unique:
  mask <-

    dplyr::mutate(
      mask,
      dupl_encrypted_file = duplicated(encrypted_file),
      ndupl_encrypted_file = cumsum(dupl_encrypted_file) %>%
        (\(n) paste0("DUPL", n)),
      encrypted_file =
        ifelse(dupl_encrypted_file,
               paste0(ndupl_encrypted_file, "_",
                      encrypted_file),
               encrypted_file))

  # Split the mask with r rows into a list of r elements, named by full
  # input file path:
  split_mask <-
    split(mask, mask$row_number) %>%
    stats::setNames(paste0(mask$folder_path, "/", mask$file))

  # Dispatch each row to its own background job. The per-row processing
  # logic lives in .process_mask_row() — extracted in Phase 1.D.1 so it
  # can be tested in isolation and swapped for in_memory / streaming
  # engines in Phases 1.D.2 / 1.D.4. The job::job() wrapper will itself
  # be replaced by mirai in Phase 1.D.6.
  purrr::map(names(split_mask), \(x) {

    # Sink args into the local frame so job::job() captures them.
    sm                   <- split_mask[[x]]
    input_path           <- x
    output_path          <- output_path
    intermediate_path    <- intermediate_path
    encryption_key       <- encryption_key
    algorithm            <- algorithm
    correspondence_table <- correspondence_table
    engine               <- engine
    chunk_size           <- chunk_size

    job::job({
      .process_mask_row(
        sm                   = sm,
        input_path           = input_path,
        output_path          = output_path,
        intermediate_path    = intermediate_path,
        encryption_key       = encryption_key,
        algorithm            = algorithm,
        correspondence_table = correspondence_table,
        engine               = engine,
        chunk_size           = chunk_size
      )
      job::export("none")
    },
    title = paste0("Encryption of ",
                   input_path %>% strsplit("/") %>%
                     purrr::map(\(xx) xx[length(xx)]) %>%
                     unlist()))
  })

  invisible(NULL)
}

#' Does the given path have a `.parquet` extension?
#'
#' Used by the dispatcher to decide whether the streaming engine is
#' applicable. Comparison is case-insensitive. No I/O — purely a name
#' check; actual openability is handled by arrow at read time.
#'
#' @param path Character(1).
#' @return Logical(1).
#' @noRd
.is_parquet <- function(path) {
  if (length(path) != 1L || is.na(path)) return(FALSE)
  grepl("\\.parquet$", path, ignore.case = TRUE)
}

#' Process one row of the encryption mask (dispatcher).
#'
#' Thin dispatcher introduced in Phase 1.D.2 and extended in Phase
#' 1.D.4.b. Routes to:
#'   - `.process_mask_row_streaming()` when `engine == "streaming"`
#'     **and** both the input file and the declared `encrypted_file`
#'     are parquet;
#'   - `.process_mask_row_in_memory()` in every other case (including
#'     `engine = "auto"` — the auto routing rule lands in 1.D.4.d and
#'     `engine = "streaming"` with non-parquet endpoints silently
#'     falls back to preserve non-regression).
#'
#' Keeping the dispatcher separate from the engines guarantees that
#' the historical code path stays strictly untouched while the
#' streaming engine evolves, protecting non-regression on existing
#' baselines.
#'
#' @inheritParams .process_mask_row_in_memory
#' @param engine One of `"auto"`, `"in_memory"`, `"streaming"`. See
#'   routing rules above.
#' @param chunk_size Integer. Forwarded to the streaming engine only;
#'   ignored by in_memory.
#' @return Invisible `NULL`.
#' @noRd
.process_mask_row <- function(sm, input_path, output_path, intermediate_path,
                              encryption_key, algorithm, correspondence_table,
                              engine = "in_memory", chunk_size = 1e6L) {

  use_streaming <- identical(engine, "streaming") &&
                   .is_parquet(input_path) &&
                   .is_parquet(sm[["encrypted_file"]])

  if (use_streaming) {
    .process_mask_row_streaming(
      sm                   = sm,
      input_path           = input_path,
      output_path          = output_path,
      intermediate_path    = intermediate_path,
      encryption_key       = encryption_key,
      algorithm            = algorithm,
      correspondence_table = correspondence_table,
      chunk_size           = chunk_size
    )
  } else {
    # `engine = "auto"` also lands here until 1.D.4.d wires it. Any
    # `engine = "streaming"` call with non-parquet endpoints silently
    # falls back to the historical engine — documented in the roxygen
    # of crypt_r().
    .process_mask_row_in_memory(
      sm                   = sm,
      input_path           = input_path,
      output_path          = output_path,
      intermediate_path    = intermediate_path,
      encryption_key       = encryption_key,
      algorithm            = algorithm,
      correspondence_table = correspondence_table
    )
  }
}

#' Process one row of the encryption mask — in-memory engine.
#'
#' Encapsulates the **historical** per-row processing logic: full load
#' of the input file into RAM via `rio::import()`, then character
#' cleanup, encryption of the requested variables, optional
#' correspondence table, and export of the final dataset + inspect
#' report. Extracted from `.process_mask_row()` in Phase 1.D.2 so that
#' the historical code path can stay strictly unchanged while the
#' streaming engine is being written in Phase 1.D.4. The parallel
#' streaming engine will live in a sibling helper
#' `.process_mask_row_streaming()`.
#'
#' @section FROZEN (Phase 1.D.3):
#' The behaviour of this function is locked by:
#'   - `tests/baseline/outputs/` (byte-level fixtures regenerated by
#'     `tests/baseline/generate_baseline.R`), and
#'   - the explicit invariant tests at the bottom of
#'     `tests/testthat/test-process_mask_row.R` (inspect xlsx layout,
#'     TC parquet distinctness, output column order).
#'
#' Do **not** edit this function for refactoring, style, or
#' "improvement" reasons. Any behavioural change — even cosmetic —
#' requires:
#'   1. A ticketed motivation in the phase plan (not an opportunistic
#'      cleanup).
#'   2. Regeneration of `tests/baseline/outputs/` in the same commit.
#'   3. Review of the impact on the private (enterprise) branch that
#'      consumes this package.
#' The `assign_to_global()` + `eval(parse(text=))` patterns below are
#' historical debt that will be retired only in Phase 1.D.6 together
#' with the move to `mirai`; until then they are intentional.
#'
#' Side effects are preserved from the historical implementation: the
#' per-variable `<var>_crypt` vectors, the final
#' `<encrypted_file_sans_ext>` dataset and (when
#' `correspondence_table = TRUE`) the `tc_<encrypted_file_sans_ext>`
#' are still assigned to `globalenv()` via `assign_to_global()`. These
#' assignments will disappear in Phase 1.D.6 (values flowing through
#' return-values and `.cryptRopen_env` instead).
#'
#' @param sm A one-row data.frame corresponding to one row of the
#'   filtered mask (columns: folder_path, file, encrypted_file,
#'   vars_to_encrypt, vars_to_remove, …).
#' @param input_path Full path to the input dataset file.
#' @param output_path,intermediate_path Directories where outputs are written.
#' @param encryption_key,algorithm,correspondence_table Forwarded from
#'   `crypt_r()`.
#' @return Invisible `NULL`. All outputs are side effects (files on
#'   disk and assignments in `globalenv()`).
#' @noRd
.process_mask_row_in_memory <- function(sm, input_path, output_path, intermediate_path,
                                        encryption_key, algorithm, correspondence_table) {

  requireNamespace("magrittr")

  try({
    # Import and clean:
    assign_to_global(
      sm[["encrypted_file"]] %>% stringr::str_remove("\\..*$"),
      rio::import(input_path, trust = TRUE) %>%
        # 0-length values into NAs:
        dplyr::mutate_if(is.character, \(x0) {
          x0[nchar(stringr::str_trim(x0)) == 0] <- NA ;
          stringr::str_trim(x0)
        }) %>%
        # Encrypt:
        (\(x3) {

          # Each variable to encrypt in a vector:
          vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
            stringr::str_split(",") %>% unlist %>%
            stringr::str_trim()

          purrr::map(vars_to_encrypt, \(v) {

            # Encryption algorithm using the digest:: package:
            assign_to_global(paste0(v, "_crypt"),
                   crypt_vector(vector = x3[[v]],
                                key = encryption_key,
                                algo = algorithm),
                   pos = globalenv())
          })

          # Fuse initial dataset and encrypted variables:
          assign_to_global(
            sm[["encrypted_file"]] %>%
              stringr::str_remove("\\..*$"),
            dplyr::bind_cols(
                purrr::map(vars_to_encrypt %>%
                             paste0("_crypt"), get) %>%
                  do.call(what = dplyr::bind_cols) %>%
                  stats::setNames(vars_to_encrypt %>%
                                    paste0("_crypt")),
                x3) %>%
              dplyr::as_tibble() %>%

              # Correspondence table:
              (\(d) {
                if (! correspondence_table) {d} else {
                  purrr::map(vars_to_encrypt, \(v2) {
                    assign_to_global(
                      sm[["encrypted_file"]] %>%
                        stringr::str_remove("\\..*$") %>%
                        (\(x4) paste0("tc_", x4)),
                      dplyr::select(d,
                                    vars_to_encrypt) %>%
                        dplyr::bind_cols(
                          purrr::map(
                            vars_to_encrypt %>%
                              paste0("_crypt"), get) %>%
                            do.call(
                              what = dplyr::bind_cols) %>%
                            stats::setNames(
                              vars_to_encrypt %>%
                                paste0("_crypt"))) %>%
                        dplyr::distinct(),
                      pos = globalenv()
                    )
                  })

                  # Export into intermediate folder:
                  rio::export(
                    sm[["encrypted_file"]] %>%
                      stringr::str_remove("\\..*$") %>%
                      (\(x4)
                        paste0("tc_", x4)) %>% get(),

                    file.path(intermediate_path,
                              sm[["encrypted_file"]] %>%
                                stringr::str_remove(
                                  "\\..*$") %>%
                                (\(x4)
                                  paste0("tc_", x4)) %>%
                                paste0(".parquet"))
                  )
                  d
                }
              }) %>%

              # Output without original variables:
              dplyr::select(- vars_to_encrypt) %>%

              # Without any other variables user want to remove
              # from output, if applicable:
              (\(dfin) {
                vars_to_remove <- sm[["vars_to_remove"]] %>%
                  stringr::str_split(",") %>% unlist %>%
                  stringr::str_trim()

                if (all(is.na(vars_to_remove))) {
                  dfin
                } else {
                  dplyr::select(dfin, - vars_to_remove)
                }
              }),
            pos = globalenv())
        }
        )
    )
  })
  invisible()

  # Export final output:
  try({
    rio::export(
      eval(parse(text = sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))),
      file.path(output_path,
                sm[["encrypted_file"]]))
  })

  # Inspect final output:
  try({
    writexl::write_xlsx(
      eval(parse(text =  sm[["encrypted_file"]] %>%
                   stringr::str_remove("\\..*$"))) %>%
        (\(g)
          inspect(g) %>%
            (\(i) rbind(c("Obs = ", nrow(g),
                          rep("", ncol(i) - 1)),
                        c("Nvars = ", nrow(i),
                          rep("", ncol(i) - 1)),
                        cbind(1:nrow(i), i)))),
      file.path(output_path,
                paste0("inspect_", sm[["encrypted_file"]],
                       ".xlsx"))
    )
  })

  invisible(NULL)
}

#' Process one row of the encryption mask — streaming engine (parquet).
#'
#' Introduced in Phase 1.D.4.b. Streams the input parquet file through
#' an arrow Scanner by chunks of `chunk_size` rows, encrypts each chunk
#' in memory, writes the result incrementally to the output parquet
#' file via `arrow::ParquetFileWriter`, and builds the correspondence
#' table by accumulating per-chunk `distinct()` rows.
#'
#' This engine handles **parquet-in / parquet-out only**. The
#' dispatcher enforces this precondition and falls back to the
#' in-memory engine otherwise, so this function does not need to
#' re-check it.
#'
#' Behavioural guarantees (vs. the in-memory engine on the same input):
#'   - Output rows are identical (same values, same types, same order).
#'   - Output column order is identical: `<var>_crypt` columns first
#'     in `vars_to_encrypt` order, then the remaining input columns in
#'     input order (`vars_to_remove` applied last).
#'   - Character cleanup is identical: `str_trim()` + empty strings → NA.
#'   - Correspondence table contents are identical (modulo row order,
#'     which was already non-deterministic in the in-memory engine
#'     through `dplyr::distinct()`).
#'   - The `inspect_*.xlsx` report has the same structure as the
#'     in-memory engine: header row from writexl, then `Obs = `,
#'     `Nvars = `, then indexed inspect rows.
#'
#' Deliberate differences with the in-memory engine (Option B, validated
#' with the user on 2026-04-22):
#'   - **No pollution of `globalenv()`**. Neither the per-var `<var>_crypt`
#'     vectors, the final `<encrypted_stem>` dataset nor the
#'     `tc_<encrypted_stem>` table are assigned anywhere visible outside
#'     the package. The correspondence table is stored in
#'     `.cryptRopen_env` (retrievable via `get_correspondence_tables()`)
#'     and on disk; the encrypted dataset is only on disk.
#'   - `assign_to_global()` + `eval(parse(text = ...))` are not used.
#'
#' @param sm,input_path,output_path,intermediate_path,encryption_key,algorithm,correspondence_table
#'   Forwarded from the dispatcher — see `.process_mask_row_in_memory()`.
#' @param chunk_size Integer(1). Arrow Scanner `batch_size`. Only
#'   affects memory usage and performance; results are invariant.
#' @return Invisible `NULL`. Side effects: files on disk + one entry
#'   in `.cryptRopen_env` when `correspondence_table = TRUE`.
#' @noRd
.process_mask_row_streaming <- function(sm, input_path, output_path, intermediate_path,
                                        encryption_key, algorithm, correspondence_table,
                                        chunk_size = 1e6L) {

  requireNamespace("magrittr")
  requireNamespace("arrow")

  encrypted_file   <- sm[["encrypted_file"]]
  encrypted_stem   <- stringr::str_remove(encrypted_file, "\\..*$")
  output_file_path <- file.path(output_path, encrypted_file)

  vars_to_encrypt <- sm[["vars_to_encrypt"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  vars_to_remove <- sm[["vars_to_remove"]] %>%
    stringr::str_split(",") %>% unlist() %>%
    stringr::str_trim()

  tc_accum <- NULL
  writer   <- NULL
  sink     <- NULL

  # --- Read / transform / write by chunks -------------------------------
  try({
    ds      <- arrow::open_dataset(input_path, format = "parquet")
    scanner <- arrow::Scanner$create(ds, batch_size = as.integer(chunk_size))
    reader  <- scanner$ToRecordBatchReader()

    repeat {
      batch <- reader$read_next_batch()
      if (is.null(batch)) break

      chunk <- dplyr::as_tibble(as.data.frame(batch))

      # Character cleanup — byte-for-byte identical to the in_memory engine:
      # trim whitespace, turn empty strings into NA.
      chunk <- dplyr::mutate(
        chunk,
        dplyr::across(dplyr::where(is.character), \(x0) {
          x0[nchar(stringr::str_trim(x0)) == 0] <- NA
          stringr::str_trim(x0)
        })
      )

      # Encrypt each requested variable.
      crypted <- purrr::map(vars_to_encrypt, \(v) {
        crypt_vector(vector = chunk[[v]], key = encryption_key,
                     algo = algorithm)
      })
      names(crypted) <- paste0(vars_to_encrypt, "_crypt")
      crypted_df <- dplyr::as_tibble(crypted)

      # Accumulate correspondence table (per-chunk distinct, then merge).
      if (correspondence_table) {
        tc_chunk <- dplyr::distinct(
          dplyr::bind_cols(
            dplyr::select(chunk, dplyr::all_of(vars_to_encrypt)),
            crypted_df
          )
        )
        tc_accum <- if (is.null(tc_accum)) tc_chunk
                    else dplyr::distinct(dplyr::bind_rows(tc_accum, tc_chunk))
      }

      # Assemble output chunk: encrypted columns first (in vars_to_encrypt
      # order), then non-encrypted input columns in input order.
      non_enc_cols <- setdiff(names(chunk), vars_to_encrypt)
      out_chunk    <- dplyr::bind_cols(
        crypted_df,
        dplyr::select(chunk, dplyr::all_of(non_enc_cols)))

      # Optional vars_to_remove.
      if (!all(is.na(vars_to_remove))) {
        to_drop <- intersect(vars_to_remove, names(out_chunk))
        if (length(to_drop) > 0L) {
          out_chunk <- dplyr::select(out_chunk, -dplyr::all_of(to_drop))
        }
      }

      arrow_tbl <- arrow::as_arrow_table(out_chunk)

      # First chunk fixes the output schema; subsequent chunks must
      # conform. Character cleanup + crypt_vector() are type-stable,
      # so the schema is stable across chunks by construction.
      # Two arrow-R quirks:
      #   - `sink` must be an OutputStream (a character path is not
      #     accepted, hence the FileOutputStream wrapper);
      #   - the default `properties` built by
      #     `ParquetWriterProperties$create()` fails unless
      #     `column_names` is provided explicitly, so we pre-build it.
      if (is.null(writer)) {
        sink   <- arrow::FileOutputStream$create(output_file_path)
        writer <- arrow::ParquetFileWriter$create(
          schema     = arrow_tbl$schema,
          sink       = sink,
          properties = arrow::ParquetWriterProperties$create(
            column_names = names(arrow_tbl)))
      }
      # Arrow-R quirk: `WriteTable` also requires a non-default
      # `chunk_size`. Use the batch size as the parquet row-group size
      # — one row group per input chunk.
      writer$WriteTable(arrow_tbl, chunk_size = arrow_tbl$num_rows)
    }

    if (!is.null(writer)) writer$Close()
    if (!is.null(sink))   sink$close()
  })

  # --- Correspondence table: store + export -----------------------------
  try({
    if (correspondence_table && !is.null(tc_accum)) {
      tc_name <- paste0("tc_", encrypted_stem)
      .store_correspondence_table(name = tc_name, df = tc_accum)
      arrow::write_parquet(
        tc_accum,
        file.path(intermediate_path,
                  paste0(tc_name, ".parquet")))
    }
  })

  # --- Inspect: re-read output, apply inspect(), write xlsx -------------
  # The double I/O (write then re-read) is acceptable because inspect()
  # needs the full data frame. The xlsx layout mirrors the in-memory
  # engine line-for-line so that non-regression on the sheet structure
  # holds across engines.
  try({
    if (file.exists(output_file_path)) {
      out_df <- as.data.frame(arrow::read_parquet(output_file_path))
      i <- inspect(out_df)
      layout <- rbind(
        c("Obs = ",   nrow(out_df), rep("", ncol(i) - 1)),
        c("Nvars = ", nrow(i),      rep("", ncol(i) - 1)),
        cbind(seq_len(nrow(i)), i))
      writexl::write_xlsx(
        layout,
        file.path(output_path,
                  paste0("inspect_", encrypted_file, ".xlsx"))
      )
    }
  })

  invisible(NULL)
}
