# WARNING - Generated by {fusen} from dev/flat_inspect.Rmd: do not edit by hand # nolint: line_length_linter.

#' Inspect a data frame
#'
#' Given a data frame as an input, this function outputs an broad view
#' of this data frame contents:
#' dimensions, list of variables and
#' systematic corresponding information (type,
#' frequence and proportion of unique values, missing and 0-length values;
#' and up to the 10 first unique values).
#' @param data_frame The data.frame to explore.
#' Need to exist in the Global Environment.
#' @param nrow Logical. If TRUE, the number of observations of
#' the dataset is rendered in addition.
#' @return Variable list of the dataset and
#' systematic informations for each variable.
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' requireNamespace("magrittr")
#' inspect(CO2)
inspect <- function(data_frame, nrow = FALSE) {

  requireNamespace("magrittr")

  # Observations:
  rows <- nrow(data_frame)
  df <- data_frame %>%

    # Date-time class correction to make it compatible with class(.x):
    dplyr::mutate_if(
      lubridate::is.POSIXct, \(x)
      as.character(x) %>% structure(class = "Date-time")) %>%

    # Compute inspection infos:
    purrr::map_df(~ {
      dplyr::tibble(
        class = class(.x),
        nb_distinct = dplyr::n_distinct(.x),
        prop_distinct = nb_distinct / rows,
        nb_na = sum(is.na(.x)),
        prop_na = nb_na / rows,
        nb_void = sum(.x == "", na.rm = TRUE),
        prop_void = nb_void / rows,
        nchars = paste(unique(sort(nchar(as.character(.x))))[
          1:min(dplyr::n_distinct(nchar(as.character(.x))), 10)],
          collapse = " / "),
        modalities = paste(sort(unique(.x))[
          1:min(dplyr::n_distinct(.x), 10)],
          collapse = " / ")
      )
    }, .id = "variables")
  if (nrow) {
    print(nrow(data_frame))
    df
  } else
    df
}
